In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import g_key

In [2]:
#Read in data and create DataFrame
weather_data = "cities.csv"
weather_data = pd.read_csv(weather_data)
weather_data.head()

,Unnamed: 0,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed
0,0,Fairbanks,64.84,-147.72,25.20,92,90,1.92
1,1,Wencheng,33.06,113.80,54.30,41,100,4.56
2,2,Macduff,57.67,-2.50,41.54,93,75,17.22
3,3,Tuatapere,-46.13,167.68,53.01,92,95,10.00
4,4,Vallenar,-28.57,-70.76,73.38,53,0,13.13

In [7]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [10]:
# Set Latitude and Longitude as locations and humidity as weight
humidity = weather_data["Humidity"].astype(float)
maxhumidity = humidity.max()
locations = weather_data[["Latitude", "Longitude"]]

In [17]:
# Create first map
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,dissipating=False, max_intensity=maxhumidity,point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Narrow down dataframe to reflect ideal conditions
ideal_temp = weather_data[(weather_data['Temperature'] > 70) & (weather_data['Temperature'] < 80)]
ideal_clouds = ideal_temp[(ideal_temp['Cloudiness'] == 0)]
ideal_df = ideal_clouds[(ideal_clouds['Wind Speed'] < 10)]
ideal_df

,Unnamed: 0,City,Latitude,Longitude,Temperature,Humidity,Cloudiness,Wind Speed
83,83,Viedma,-40.81,-63.00,76.98,18,0,2.46
93,93,Jalu,29.03,21.55,73.20,17,0,8.23
204,204,Yulara,-25.24,130.99,75.20,18,0,6.93
318,318,Kununurra,-15.77,128.73,71.60,88,0,5.66
460,460,Katherine,-14.47,132.27,75.20,78,0,4.90
502,502,Les Cayes,18.20,-73.75,79.68,67,0,7.83
512,512,Doha,25.29,51.53,75.22,53,0,8.05
529,529,Bowen,-20.02,148.23,70.03,94,0,3.36